//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oleg_ivo.WAGO.Configuration
{
    
    
    /// <summary>
    /// The DMISConfigurationSection Configuration Section.
    /// </summary>
    public partial class DMISConfigurationSection : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the DMISConfigurationSection Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string DMISConfigurationSectionSectionName = "dMISConfigurationSection";
        
        /// <summary>
        /// Gets the DMISConfigurationSection instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public static global::Oleg_ivo.WAGO.Configuration.DMISConfigurationSection Instance
        {
            get
            {
                return ((global::Oleg_ivo.WAGO.Configuration.DMISConfigurationSection)(global::System.Configuration.ConfigurationManager.GetSection(global::Oleg_ivo.WAGO.Configuration.DMISConfigurationSection.DMISConfigurationSectionSectionName)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Oleg_ivo.WAGO.Configuration.DMISConfigurationSection.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::Oleg_ivo.WAGO.Configuration.DMISConfigurationSection.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region DMISConfigurations Property
        /// <summary>
        /// The XML name of the <see cref="DMISConfigurations"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string DMISConfigurationsPropertyName = "dMISConfigurations";
        
        /// <summary>
        /// Gets or sets the DMISConfigurations.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The DMISConfigurations.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Oleg_ivo.WAGO.Configuration.DMISConfigurationSection.DMISConfigurationsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElementCollection DMISConfigurations
        {
            get
            {
                return ((global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElementCollection)(base[global::Oleg_ivo.WAGO.Configuration.DMISConfigurationSection.DMISConfigurationsPropertyName]));
            }
            set
            {
                base[global::Oleg_ivo.WAGO.Configuration.DMISConfigurationSection.DMISConfigurationsPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace Oleg_ivo.WAGO.Configuration
{
    
    
    /// <summary>
    /// A collection of DMISConfigurationElement instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElementCollection.DMISConfigurationElementPropertyName)]
    public partial class DMISConfigurationElementCollection : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string DMISConfigurationElementPropertyName = "dMISConfig";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override string ElementName
        {
            get
            {
                return global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElementCollection.DMISConfigurationElementPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElementCollection.DMISConfigurationElementPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement)(element)).Name;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement this[int index]
        {
            get
            {
                return ((global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement this[object name]
        {
            get
            {
                return ((global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement)(base.BaseGet(name)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="dMISConfig">The <see cref="global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Add(global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement dMISConfig)
        {
            base.BaseAdd(dMISConfig);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="dMISConfig">The <see cref="global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Remove(global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement dMISConfig)
        {
            base.BaseRemove(this.GetElementKey(dMISConfig));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement GetItemAt(int index)
        {
            return ((global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement GetItemByKey(string name)
        {
            return ((global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement)(base.BaseGet(((object)(name)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace Oleg_ivo.WAGO.Configuration
{
    
    
    /// <summary>
    /// The DMISConfigurationElement Configuration Element.
    /// </summary>
    public partial class DMISConfigurationElement : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Name Property
        /// <summary>
        /// The XML name of the <see cref="Name"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string NamePropertyName = "name";
        
        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Name.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement.NamePropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Name
        {
            get
            {
                return ((string)(base[global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement.NamePropertyName]));
            }
            set
            {
                base[global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement.NamePropertyName] = value;
            }
        }
        #endregion
        
        #region IsEmulationMode Property
        /// <summary>
        /// The XML name of the <see cref="IsEmulationMode"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string IsEmulationModePropertyName = "isEmulationMode";
        
        /// <summary>
        /// Gets or sets the IsEmulationMode.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The IsEmulationMode.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement.IsEmulationModePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual bool IsEmulationMode
        {
            get
            {
                return ((bool)(base[global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement.IsEmulationModePropertyName]));
            }
            set
            {
                base[global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement.IsEmulationModePropertyName] = value;
            }
        }
        #endregion
        
        #region LoadOptions Property
        /// <summary>
        /// The XML name of the <see cref="LoadOptions"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string LoadOptionsPropertyName = "loadOptions";
        
        /// <summary>
        /// Gets or sets the LoadOptions.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The LoadOptions.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement.LoadOptionsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElementCollection LoadOptions
        {
            get
            {
                return ((global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElementCollection)(base[global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement.LoadOptionsPropertyName]));
            }
            set
            {
                base[global::Oleg_ivo.WAGO.Configuration.DMISConfigurationElement.LoadOptionsPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace Oleg_ivo.WAGO.Configuration
{
    
    
    /// <summary>
    /// A collection of LoadOptionsConfigurationElement instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElementCollection.LoadOptionsConfigurationElementPropertyName)]
    public partial class LoadOptionsConfigurationElementCollection : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string LoadOptionsConfigurationElementPropertyName = "loadOptionsConfigurationElement";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override string ElementName
        {
            get
            {
                return global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElementCollection.LoadOptionsConfigurationElementPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElementCollection.LoadOptionsConfigurationElementPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement)(element)).FieldBusType;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement this[int index]
        {
            get
            {
                return ((global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement"/> with the specified key.
        /// </summary>
        /// <param name="fieldBusType">The key of the <see cref="global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement this[object fieldBusType]
        {
            get
            {
                return ((global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement)(base.BaseGet(fieldBusType)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="loadOptionsConfigurationElement">The <see cref="global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Add(global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement loadOptionsConfigurationElement)
        {
            base.BaseAdd(loadOptionsConfigurationElement);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="loadOptionsConfigurationElement">The <see cref="global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Remove(global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement loadOptionsConfigurationElement)
        {
            base.BaseRemove(this.GetElementKey(loadOptionsConfigurationElement));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement GetItemAt(int index)
        {
            return ((global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement"/> with the specified key.
        /// </summary>
        /// <param name="fieldBusType">The key of the <see cref="global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement GetItemByKey(string fieldBusType)
        {
            return ((global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement)(base.BaseGet(((object)(fieldBusType)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace Oleg_ivo.WAGO.Configuration
{
    
    
    /// <summary>
    /// The LoadOptionsConfigurationElement Configuration Element.
    /// </summary>
    public partial class LoadOptionsConfigurationElement : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region FieldBusType Property
        /// <summary>
        /// The XML name of the <see cref="FieldBusType"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string FieldBusTypePropertyName = "fieldBusType";
        
        /// <summary>
        /// Gets or sets the FieldBusType.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The FieldBusType.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement.FieldBusTypePropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false, DefaultValue="Unknown")]
        public virtual string FieldBusType
        {
            get
            {
                return ((string)(base[global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement.FieldBusTypePropertyName]));
            }
            set
            {
                base[global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement.FieldBusTypePropertyName] = value;
            }
        }
        #endregion
        
        #region FieldNodesLevel Property
        /// <summary>
        /// The XML name of the <see cref="FieldNodesLevel"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string FieldNodesLevelPropertyName = "fieldNodesLevel";
        
        /// <summary>
        /// Gets or sets the FieldNodesLevel.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The FieldNodesLevel.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement.FieldNodesLevelPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::Oleg_ivo.WAGO.Configuration.LevelLoadOptionsConfigElement FieldNodesLevel
        {
            get
            {
                return ((global::Oleg_ivo.WAGO.Configuration.LevelLoadOptionsConfigElement)(base[global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement.FieldNodesLevelPropertyName]));
            }
            set
            {
                base[global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement.FieldNodesLevelPropertyName] = value;
            }
        }
        #endregion
        
        #region PhysicalChannelsLevel Property
        /// <summary>
        /// The XML name of the <see cref="PhysicalChannelsLevel"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string PhysicalChannelsLevelPropertyName = "physicalChannelsLevel";
        
        /// <summary>
        /// Gets or sets the PhysicalChannelsLevel.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The PhysicalChannelsLevel.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement.PhysicalChannelsLevelPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::Oleg_ivo.WAGO.Configuration.LevelLoadOptionsConfigElement PhysicalChannelsLevel
        {
            get
            {
                return ((global::Oleg_ivo.WAGO.Configuration.LevelLoadOptionsConfigElement)(base[global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement.PhysicalChannelsLevelPropertyName]));
            }
            set
            {
                base[global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement.PhysicalChannelsLevelPropertyName] = value;
            }
        }
        #endregion
        
        #region LogicalChannelsLevel Property
        /// <summary>
        /// The XML name of the <see cref="LogicalChannelsLevel"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string LogicalChannelsLevelPropertyName = "logicalChannelsLevel";
        
        /// <summary>
        /// Gets or sets the LogicalChannelsLevel.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The LogicalChannelsLevel.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement.LogicalChannelsLevelPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::Oleg_ivo.WAGO.Configuration.LevelLoadOptionsConfigElement LogicalChannelsLevel
        {
            get
            {
                return ((global::Oleg_ivo.WAGO.Configuration.LevelLoadOptionsConfigElement)(base[global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement.LogicalChannelsLevelPropertyName]));
            }
            set
            {
                base[global::Oleg_ivo.WAGO.Configuration.LoadOptionsConfigurationElement.LogicalChannelsLevelPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace Oleg_ivo.WAGO.Configuration
{
    
    
    /// <summary>
    /// The LevelLoadOptionsConfigElement Configuration Element.
    /// </summary>
    public partial class LevelLoadOptionsConfigElement : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region LoadSavedConfiguration Property
        /// <summary>
        /// The XML name of the <see cref="LoadSavedConfiguration"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string LoadSavedConfigurationPropertyName = "loadSavedConfiguration";
        
        /// <summary>
        /// Gets or sets the LoadSavedConfiguration.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The LoadSavedConfiguration.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Oleg_ivo.WAGO.Configuration.LevelLoadOptionsConfigElement.LoadSavedConfigurationPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual bool LoadSavedConfiguration
        {
            get
            {
                return ((bool)(base[global::Oleg_ivo.WAGO.Configuration.LevelLoadOptionsConfigElement.LoadSavedConfigurationPropertyName]));
            }
            set
            {
                base[global::Oleg_ivo.WAGO.Configuration.LevelLoadOptionsConfigElement.LoadSavedConfigurationPropertyName] = value;
            }
        }
        #endregion
        
        #region ComputeCurrentConfiguration Property
        /// <summary>
        /// The XML name of the <see cref="ComputeCurrentConfiguration"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string ComputeCurrentConfigurationPropertyName = "computeCurrentConfiguration";
        
        /// <summary>
        /// Gets or sets the ComputeCurrentConfiguration.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The ComputeCurrentConfiguration.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::Oleg_ivo.WAGO.Configuration.LevelLoadOptionsConfigElement.ComputeCurrentConfigurationPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual bool ComputeCurrentConfiguration
        {
            get
            {
                return ((bool)(base[global::Oleg_ivo.WAGO.Configuration.LevelLoadOptionsConfigElement.ComputeCurrentConfigurationPropertyName]));
            }
            set
            {
                base[global::Oleg_ivo.WAGO.Configuration.LevelLoadOptionsConfigElement.ComputeCurrentConfigurationPropertyName] = value;
            }
        }
        #endregion
    }
}
