ALTER TABLE [dbo].[ProtocolException]
    ADD CONSTRAINT [PK_ProtocolException] PRIMARY KEY CLUSTERED ([ProtocolEventId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

