ALTER TABLE [dbo].[EventType]
    ADD CONSTRAINT [PK_EventType] PRIMARY KEY CLUSTERED ([EventTypeId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

